### ISSUE TITLE
error when contacting the assistant

### ISSUE THREAD

**Issue by DeadIord** [samuelgjekic/OpenAI-Assistants-API-Wrapper-for-.NET#11]
on the line
`  
var assistants = await aiService.GetAssistantById(AssistantsId);
`
the following exception is displayed:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at OpenAi_Assistant.Services.AssistantService.GetAssistantById(String assistant_id)
   at OpenAi_Assistant.Services.OpenAiAssistantService.GetAssistantById(String assistant_id)
```
What is the reason for this? Considering that everything was fine yesterday

**Comment by DeadIord** [comment]
to be more precise, in this method, during the assignment of data to the AssistantModel when "response.IsSuccessStatusCode = true"
```
 public async Task<AssistantModel> GetAssistantById(string assistant_id)
 {
     string requestUri = "https://api.openai.com/v1/assistants/" + assistant_id;
     HttpResponseMessage response = await httpClient.GetAsync(requestUri);
     object obj = JsonConvert.DeserializeObject<object>(await response.Content.ReadAsStringAsync());
     if (response.IsSuccessStatusCode)
     {
         AssistantModel assistantModel = new AssistantModel();
         assistantModel.id = ((dynamic)obj)?.id;
         assistantModel.created_at = ((dynamic)obj)?.created_at;
         assistantModel.instructions = ((dynamic)obj)?.instructions;
         assistantModel.name = ((dynamic)obj)?.name;
         assistantModel.apimodel = ((dynamic)obj)?.model;
         assistantModel.tool = ((dynamic)obj)?.tools[0]?.type;
         return assistantModel;
     }

     return null;
 }
```
